import { useUiClass } from '../../shared/ui/ui-theme.ts'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router'
import { Badge, Button, Card, ConfirmationDialog, Icon, Input, Modal } from '../../shared/ui/index.ts'
import { PageHeader } from '../../shared/components/PageHeader.tsx'
import { StatusBanner } from '../../shared/components/StatusBanner.tsx'
import { createEventSetupProductionServices } from '../../infrastructure/composition/event-setup-production.ts'
import { signalProductionWorkspaceChanged, useProductionWorkspace } from '../../app/workspace/ProductionWorkspaceContext.tsx'
import type { Event } from '../../domain/events/event.types.ts'
import type { EventId } from '../../domain/shared/identifiers.ts'
import { formatEventTimestamp, toCanonicalTimestamp, toDatetimeLocal } from './event-schedule.ts'
import { isEventNameValid } from './event-form.ts'
import { formatProductionNumber, productionDomainLabel } from '../../shared/localization/production-locale.ts'

type EventSummary = { readonly event: Event; readonly participantCount: number; readonly categoryCount: number; readonly liveSessionCount: number; readonly blockedSessionCount: number }
type EventForm = { readonly name: string; readonly description: string; readonly scheduledAt: string }
const empty: EventForm = { name: '', description: '', scheduledAt: '' }

export function EventsPage() {
  const ui = useUiClass()
  const services = useMemo(() => createEventSetupProductionServices(), [])
  const workspace = useProductionWorkspace(); const navigate = useNavigate()
  const [items, setItems] = useState<EventSummary[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<Event | null>(null)
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false)
  const [activating, setActivating] = useState<Event | null>(null); const [deleting, setDeleting] = useState<EventSummary | null>(null); const [deleteConfirmation, setDeleteConfirmation] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(null); try { await services.open(); const events = await services.events.findAll(); setItems(await Promise.all(events.map(async (event) => { const [participantCount, categories, sessions] = await Promise.all([services.participants.countByEventId(event.id), services.categories.findByEventId(event.id), services.sessions.findByEventId(event.id)]); return { event, participantCount, categoryCount: categories.length, liveSessionCount: sessions.filter((s) => s.mode === 'live').length, blockedSessionCount: sessions.filter((s) => s.status === 'drawing' || s.status === 'pending-confirmation').length } }))) } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Acara tidak dapat dibaca dari penyimpanan lokal.') } finally { setLoading(false) } }, [services])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  function beginEdit(event: Event) { setEditing(event); setForm({ name: event.name, description: event.description ?? '', scheduledAt: toDatetimeLocal(event.scheduledAt) }); setSaved(false); setError(null) }
  function resetForm() { setEditing(null); setForm(empty); setSaved(false) }
  async function submit() { if (submitting) return; setSubmitting(true); setError(null); try { const draft = { ...form, scheduledAt: toCanonicalTimestamp(form.scheduledAt) }; if (editing === null) await services.service.createEvent(draft); else await services.service.updateEvent(editing, draft); resetForm(); setSaved(true); signalProductionWorkspaceChanged(); await load() } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Acara tidak dapat disimpan.') } finally { setSubmitting(false) } }
  async function select(eventId: EventId) { if (submitting) return; setSubmitting(true); setError(null); try { await services.service.selectEvent(eventId); signalProductionWorkspaceChanged(); await load() } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Acara tidak dapat dipilih.') } finally { setSubmitting(false) } }
  async function manageCategories(event: Event) { if (workspace.status !== 'ready' || workspace.event.id !== event.id) await select(event.id); navigate('/prize-categories') }
  async function activate(event: Event) { if (submitting) return; setSubmitting(true); try { await services.service.activateEvent(event.id); setActivating(null); setSaved(true); signalProductionWorkspaceChanged(); await load() } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Acara tidak dapat diaktifkan.') } finally { setSubmitting(false) } }
  async function deleteEvent(summary: EventSummary) { if (submitting || summary.blockedSessionCount > 0 || summary.event.status === 'live') return; setSubmitting(true); setError(null); try { await services.events.deletePermanently(summary.event.id); setDeleting(null); setDeleteConfirmation(''); setSaved(true); signalProductionWorkspaceChanged(); await load() } catch (cause: unknown) { setError(cause instanceof Error ? cause.message : 'Acara tidak dapat dihapus dengan aman.') } finally { setSubmitting(false) } }

  return <section className="events-page" aria-labelledby="events-title"><PageHeader eyebrow="Pengaturan produksi" headingId="events-title" title="Acara" description="Buat atau pilih Acara untuk memulai pengaturan produksi." />
    {saved ? <StatusBanner badge="Tersimpan" title="Tindakan Acara selesai" tone="success">Record berhasil dibaca kembali dari IndexedDB.</StatusBanner> : null}{error ? <StatusBanner badge="Kesalahan penyimpanan atau validasi" title="Tindakan Acara tidak dapat diselesaikan" tone="warning">{error}</StatusBanner> : null}
    <div className="events-page__layout"><Card padding="md" tone="raised" className="events-page__form-card"><div className="events-page__card-heading"><div><p className="events-page__eyebrow">{editing === null ? 'Record ruang kerja baru' : 'Record draf'}</p><h2>{editing === null ? 'Buat Acara' : 'Edit draf Acara'}</h2></div></div><form className="events-page__form" onSubmit={(e) => { e.preventDefault(); void submit() }}><Input label="Nama Acara" value={form.name} required maxLength={120} onChange={(e) => setForm({ ...form, name: e.target.value })} /><label className={ui('ui-field')}><span className={ui('ui-field__label')}>Deskripsi</span><textarea className={ui('ui-input')} maxLength={500} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className={ui('ui-field')}><span className={ui('ui-field__label')}>Jadwal</span><input className={ui('ui-input')} type="datetime-local" value={form.scheduledAt} onChange={(e) => setForm({ ...form, scheduledAt: e.target.value })} /></label><div className="page-header__actions"><Button type="submit" disabled={!isEventNameValid(form.name)} isLoading={submitting}>{editing === null ? 'Buat Acara' : 'Simpan perubahan draf'}</Button>{editing !== null ? <Button type="button" variant="secondary" onClick={resetForm}>Batal</Button> : null}</div></form></Card>
      <Card padding="md" tone="raised" className="events-page__list-card"><div className="events-page__card-heading"><div><p className="events-page__eyebrow">Alur kerja</p><h2>Acara tersimpan</h2></div><span className="events-page__record-count">{formatProductionNumber(items.length)} record</span></div>{loading ? <p role="status">Memuat Acara…</p> : items.length === 0 ? <p role="status">Belum ada Acara. Buat Acara pertama untuk memulai pengaturan.</p> : <ul className="events-page__list">{items.map((summary) => { const { event, participantCount, categoryCount, liveSessionCount, blockedSessionCount } = summary; const isCurrent = workspace.status === 'ready' && workspace.event.id === event.id; const blocked = blockedSessionCount > 0 || event.status === 'live'; return <li key={event.id} className={`events-page__event-card${isCurrent ? ' events-page__event-card--current' : ''}`}><div className="events-page__event-main"><div className="events-page__event-heading"><h3>{event.name}</h3><div className="events-page__badges">{isCurrent ? <Badge variant="info">AKTIF</Badge> : null}<Badge variant={event.status === 'live' ? 'live' : event.status === 'draft' ? 'practice' : 'neutral'}>{productionDomainLabel(event.status).toUpperCase()}</Badge>{event.status !== 'draft' && event.status !== 'live' ? <Badge variant="neutral">HANYA BACA</Badge> : null}</div></div><p className="events-page__summary">{formatProductionNumber(participantCount)} peserta · {formatProductionNumber(categoryCount)} kategori hadiah · {formatProductionNumber(liveSessionCount)} sesi Live</p><dl className="events-page__metadata"><div><dt>Jadwal</dt><dd>{formatEventTimestamp(event.scheduledAt)}</dd></div><div><dt>Diperbarui</dt><dd>{formatEventTimestamp(event.updatedAt)}</dd></div></dl></div><div className="events-page__actions">{isCurrent ? <span className="events-page__current-label">Acara aktif</span> : <Button size="sm" variant="secondary" disabled={submitting || event.status === 'archived'} onClick={() => void select(event.id)}>Jadikan Aktif</Button>}{event.status === 'draft' ? <Button size="sm" variant="quiet" onClick={() => beginEdit(event)}>Edit draf</Button> : null}{event.status === 'draft' ? <Button size="sm" variant="primary" disabled={submitting} onClick={() => setActivating(event)}>Aktifkan Acara</Button> : null}<Button size="sm" variant="quiet" disabled={submitting} onClick={() => void manageCategories(event)}>Kelola Kategori Hadiah</Button>{blocked ? <span className="events-page__readonly" title="Selesaikan operasi undian aktif terlebih dahulu.">Dilindungi</span> : <Button size="sm" variant="danger" disabled={submitting} onClick={() => { setDeleting(summary); setDeleteConfirmation('') }}>Hapus Permanen</Button>}</div></li> })}</ul>}</Card></div>
    <ConfirmationDialog open={activating !== null} title={`Aktifkan ${activating?.name ?? 'Acara'}?`} confirmLabel="Aktifkan Acara" confirmDisabled={submitting} confirmLoading={submitting} onCancel={() => setActivating(null)} onConfirm={() => { if (activating !== null) void activate(activating) }} consequence="Pastikan pengaturan Acara sudah benar sebelum melanjutkan." />
    <Modal headerIcon={<Icon name="Trash2" />} headerIconTone="danger" open={deleting !== null} title="HAPUS ACARA SECARA PERMANEN" onClose={() => { if (!submitting) { setDeleting(null); setDeleteConfirmation('') } }} footer={<><Button icon={<Icon name="CircleX" />} variant="secondary" onClick={() => { setDeleting(null); setDeleteConfirmation('') }}>Batal</Button><Button icon={<Icon name="Trash2" />} variant="danger" disabled={submitting || (deleting !== null && deleting.liveSessionCount > 0 && deleteConfirmation !== deleting.event.name)} isLoading={submitting} onClick={() => { if (deleting !== null) void deleteEvent(deleting) }}>Hapus Acara Permanen</Button></>}>{deleting ? <><p><strong>{deleting.event.name}</strong></p><p>Tindakan ini menghapus Acara beserta seluruh record lokal miliknya secara permanen. Tindakan tidak dapat dibatalkan.</p><ul><li>{formatProductionNumber(deleting.participantCount)} Peserta</li><li>{formatProductionNumber(deleting.categoryCount)} Kategori Hadiah</li><li>{formatProductionNumber(deleting.liveSessionCount)} Sesi Undian</li></ul>{deleting.liveSessionCount > 0 ? <Input label={`Ketik “${deleting.event.name}” untuk mengonfirmasi`} value={deleteConfirmation} onChange={(e) => setDeleteConfirmation(e.target.value)} /> : <p>Konfirmasi eksplisit diperlukan untuk Acara pengaturan yang belum digunakan ini.</p>}</> : null}</Modal>
  </section>
}
