import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore, type FormEvent } from 'react'
import { Link } from 'react-router'
import { useProductionAudiencePublisher, useProductionWorkspace } from '../../app/workspace/ProductionWorkspaceContext.tsx'
import { createEventSettingsService } from '../../application/settings/event-settings-service.ts'
import { createDisplayConfigurationService } from '../../application/display/display-configuration-service.ts'
import { getDisplayConnectionStatus, subscribeDisplayConnectionStatus, type DisplayConnectionStatus } from '../../application/display-transport/connection-status.ts'
import type { EventSettings, LocalAsset } from '../../domain/settings/event-settings.types.ts'
import { parseDrawSessionId } from '../../domain/shared/identifiers.ts'
import { createDrawSetupProductionServices } from '../../infrastructure/composition/draw-command-production.ts'
import { PageHeader } from '../../shared/components/PageHeader.tsx'
import { StatusBanner } from '../../shared/components/StatusBanner.tsx'
import { Button } from '../../shared/ui/Button.tsx'
import { AudiencePreviewSurface } from '../../ui/audience/AudiencePreviewSurface.tsx'
import { settingsEqual } from './production-settings-draft.ts'
import { SettingsSaveToast } from './SettingsSaveToast.tsx'

const resolutions = [{ label: '1920 Ã— 1080 (Full HD)', width: 1920, height: 1080 }, { label: '3840 Ã— 2160 (4K UHD)', width: 3840, height: 2160 }, { label: '1280 Ã— 720 (HD)', width: 1280, height: 720 }] as const
const labels: Record<DisplayConnectionStatus, string> = { 'setup-required': 'Setup required', waiting: 'Waiting', connected: 'Connected', reconnecting: 'Reconnecting', unavailable: 'Unavailable', 'publication-failed': 'Publication failed' }
const assetFromFile = (file: File): LocalAsset => ({ name: file.name, type: file.type, size: file.size, blob: file })
function errorText(error: unknown): string { return error instanceof Error ? error.message : 'Settings could not be saved safely.' }
type SettingsSaveState = 'loading' | 'persisted' | 'unsaved' | 'saving' | 'saved' | 'error'
type SettingsToast = { readonly kind: 'success' | 'error'; readonly message: string }

export function ProductionSettingsPage() {
  const workspace = useProductionWorkspace()
  const audience = useProductionAudiencePublisher()
  const services = useMemo(() => createDrawSetupProductionServices(), [])
  const settingsService = useMemo(() => createEventSettingsService(services.eventSettings), [services])
  const displayService = useMemo(() => createDisplayConfigurationService({ events: services.events, configurations: services.displayConfigurations! }), [services])
  const [settings, setSettings] = useState<EventSettings | null>(null)
  const [persistedSettings, setPersistedSettings] = useState<EventSettings | null>(null)
  const [section, setSection] = useState<'branding' | 'presentation' | 'audio' | 'display'>('branding')
  const [resolution, setResolution] = useState('1920x1080')
  const [persistedResolution, setPersistedResolution] = useState('1920x1080')
  const [settingsState, setSettingsState] = useState<SettingsSaveState>('loading')
  const [message, setMessage] = useState<string | null>(null)
  const [toast, setToast] = useState<SettingsToast | null>(null)
  const displayStatusKey = workspace.status === 'ready' && workspace.displayConfiguration !== null ? `${workspace.event.id}:${workspace.displayConfiguration.id}` : 'unconfigured'
  const connection = useSyncExternalStore((listener) => subscribeDisplayConnectionStatus(displayStatusKey, listener), (): DisplayConnectionStatus => getDisplayConnectionStatus(displayStatusKey), (): DisplayConnectionStatus => 'waiting')
  const initiallyTestActive = audience.getDiagnostics()?.retainedPublicState === 'display-test'
  const [testing, setTesting] = useState(initiallyTestActive)
  const [testVisibility, setTestVisibility] = useState<'inactive' | 'publishing' | 'visible' | 'stopping' | 'standby' | 'failed'>(initiallyTestActive ? 'visible' : 'inactive')
  const [popupBlocked, setPopupBlocked] = useState(false)
  const [audioMessage, setAudioMessage] = useState('')
  const testVisibilityRef = useRef(testVisibility)
  useEffect(() => { testVisibilityRef.current = testVisibility }, [testVisibility])
  const load = useCallback(async () => {
    if (workspace.status !== 'ready') return
    setSettingsState('loading')
    try { await services.open(); const loaded = await settingsService.readForEvent(workspace.event); const loadedResolution = `${workspace.displayConfiguration?.targetResolution.width ?? 1920}x${workspace.displayConfiguration?.targetResolution.height ?? 1080}`; setSettings(loaded); setPersistedSettings(loaded); setResolution(loadedResolution); setPersistedResolution(loadedResolution); setSettingsState('persisted') } catch (error: unknown) { setSettingsState('error'); setMessage(errorText(error)) }
  }, [services, settingsService, workspace])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  useEffect(() => audience.subscribe((status) => { const retainedState = audience.getDiagnostics()?.retainedPublicState; if (retainedState === 'display-test') { setTesting(true); setTestVisibility('visible') }; if (retainedState === 'standby' && testVisibilityRef.current !== 'publishing') { setTesting(false); setTestVisibility('standby') }; if (status.kind === 'snapshot-applied' && status.publicState === 'display-test') { setTesting(true); setTestVisibility('visible') }; if (status.kind === 'snapshot-applied' && status.publicState === 'standby' && testVisibilityRef.current === 'stopping') { setTesting(false); setTestVisibility('standby') }; if (status.kind === 'transport-error') { setTestVisibility('failed'); setMessage('The display snapshot could not be published safely.') } }), [audience])
  if (workspace.status !== 'ready') return <section aria-labelledby="settings-title"><PageHeader eyebrow="Production workspace" headingId="settings-title" title="Settings" description="An active Event is required." /><StatusBanner badge="Event required" title="Display configuration not configured" tone="warning">No editable controls are shown without authoritative Event context. Select an active Event to configure production settings.</StatusBanner><Link className="ui-button ui-button--secondary" to="/events">Open Event management</Link></section>
  if (settings === null) return <section aria-busy="true"><PageHeader eyebrow="Production workspace" headingId="settings-title" title="Settings" description="Reading authoritative Event settingsâ€¦" />{settingsState === 'error' ? <StatusBanner badge="Storage error" title="Settings unavailable" tone="warning">{message}</StatusBanner> : null}</section>
  const event = workspace.event
  const activeDisplay = workspace.displayConfiguration
  const currentSettings = settings
  const displayUrl = activeDisplay === null ? null : `/display?eventId=${encodeURIComponent(event.id)}&displayConfigurationId=${encodeURIComponent(activeDisplay.id)}`
  const selected = resolutions.find((item) => `${item.width}x${item.height}` === resolution) ?? resolutions[0]
  const dirty = persistedSettings !== null && (!settingsEqual(currentSettings, persistedSettings) || resolution !== persistedResolution)
  const sectionDetails = { branding: { label: 'Branding', eyebrow: 'BRANDING', title: 'Event identity', description: 'Define the public identity used across the Audience Display.' }, presentation: { label: 'Presentation', eyebrow: 'PRESENTATION', title: 'Presentation behavior', description: 'Set the public content boundary and blackout appearance.' }, audio: { label: 'Audio', eyebrow: 'AUDIO', title: 'Audio cues', description: 'Configure the optional cue used during public reveals.' }, display: { label: 'Display', eyebrow: 'DISPLAY', title: 'Audience Display', description: 'Control the public display connection and target framing.' } } as const
  const currentSection = sectionDetails[section]
  const effectiveSaveState: SettingsSaveState = settingsState === 'saving' ? 'saving' : dirty ? 'unsaved' : settingsState
  const statusLabel = effectiveSaveState === 'saving' ? 'Saving' : effectiveSaveState === 'unsaved' ? 'Unsaved changes' : effectiveSaveState === 'error' ? 'Needs attention' : 'Persisted'
  async function save(eventSubmit: FormEvent<HTMLFormElement>) { eventSubmit.preventDefault(); if (settingsState === 'saving' || !dirty) return; setSettingsState('saving'); setMessage(null); setToast(null); try { const saved = await settingsService.saveForEvent(event, { ...currentSettings }); if (activeDisplay !== null) await displayService.saveForEvent(event, { targetResolution: { width: selected.width, height: selected.height }, safeAreaMargin: saved.safeAreaMargin, blackoutAppearance: saved.blackoutAppearance === 'event-surface' ? 'pure-black' : saved.blackoutAppearance }, activeDisplay); setSettings(saved); setPersistedSettings(saved); setPersistedResolution(resolution); setSettingsState('saved'); setToast({ kind: 'success', message: `${currentSection.label} settings saved` }) } catch (error: unknown) { setSettingsState('error'); setMessage(errorText(error)); setToast({ kind: 'error', message: `${currentSection.label} settings could not be saved. Try again.` }) } }
  function fileChange(field: 'logo' | 'background' | 'revealCue', file: File | undefined) { if (file !== undefined) { setSettings((current) => current === null ? current : { ...current, [field]: assetFromFile(file) }); setSettingsState('unsaved') } }
  function openAudience() { if (displayUrl !== null) setPopupBlocked(window.open(displayUrl, '_blank', 'noopener,noreferrer') === null) }
  function publishTest(displayTest: boolean) { if (activeDisplay === null) return; const parsed = parseDrawSessionId(event.id); if (!parsed.ok) { setMessage('The active Event cannot safely scope a display test.'); return }; if (!displayTest) { setTestVisibility('stopping'); setTesting(false) } else { setTesting(true); setTestVisibility('publishing') }; const result = audience.publish({ drawSessionId: parsed.value, stage: 'standby', blackoutRequested: false, displayTest, eventName: currentSettings.displayName, eventSubtitle: currentSettings.subtitle, primaryColor: currentSettings.primaryColor, accentColor: currentSettings.accentColor, logo: currentSettings.logo === undefined ? undefined : { type: currentSettings.logo.type, blob: currentSettings.logo.blob }, background: currentSettings.background === undefined ? undefined : { type: currentSettings.background.type, blob: currentSettings.background.blob }, blackoutAppearance: currentSettings.blackoutAppearance, safeAreaMargin: currentSettings.safeAreaMargin }); if (!result.ok) setTestVisibility('failed') }
  async function testAudio() { if (!currentSettings.revealCue) { setAudioMessage('Choose a local reveal cue first.'); return }; try { const audio = new Audio(URL.createObjectURL(currentSettings.revealCue.blob)); audio.volume = currentSettings.masterVolume / 100; await audio.play(); setAudioMessage('Cue played after your action.'); audio.onended = () => URL.revokeObjectURL(audio.src) } catch { setAudioMessage('Browser audio permission is required; press Test Audio again after allowing playback.') } }
  return <section aria-labelledby="settings-title" className="production-settings"><PageHeader actions={displayUrl === null ? undefined : <Button type="button" variant="secondary" onClick={openAudience}>Open Audience Display</Button>} eyebrow="Production workspace" headingId="settings-title" title="Settings" description={`${event.name} Â· authoritative Event presentation`} />{message ? <StatusBanner badge="Settings" title="Action needs attention" tone="warning">{message}</StatusBanner> : null}{toast ? <SettingsSaveToast key={`${toast.kind}:${toast.message}`} kind={toast.kind} message={toast.message} onDismiss={() => setToast(null)} /> : null}<div className="settings-workspace"><nav aria-label="Settings sections" className="settings-section-nav"><p>SETTINGS</p>{(['branding', 'presentation', 'audio', 'display'] as const).map((item, index) => <button type="button" key={item} className={section === item ? 'is-active' : ''} aria-current={section === item ? 'page' : undefined} onClick={() => setSection(item)}><span aria-hidden="true">{String(index + 1).padStart(2, '0')}</span><strong>{sectionDetails[item].label}</strong></button>)}</nav><div className="settings-content"><article className="settings-card"><div className="settings-card__heading"><div><p className="settings-card__eyebrow">{currentSection.eyebrow}</p><h2>{currentSection.title}</h2><p className="settings-card__description">{currentSection.description}</p></div><span className={`settings-authority settings-authority--${statusLabel.toLowerCase().replace(' ', '-')}`}>{statusLabel}</span></div><form onSubmit={save} aria-label={`${section} settings`}>
    {section === 'branding' ? <div className="settings-branding-layout"><div className="settings-form-grid settings-form-grid--branding"><label>Public display name<input value={settings.displayName} onChange={(e) => setSettings({ ...settings, displayName: e.target.value })} /></label><label>Public subtitle<input value={settings.subtitle} onChange={(e) => setSettings({ ...settings, subtitle: e.target.value })} /></label><ColorField label="Primary color" value={settings.primaryColor} onChange={(value) => setSettings({ ...settings, primaryColor: value })} /><ColorField label="Accent color" value={settings.accentColor} onChange={(value) => setSettings({ ...settings, accentColor: value })} /></div><div className="settings-asset-grid"><AssetField label="Event logo" asset={settings.logo} accept="image/*" onFile={(file) => fileChange('logo', file)} onRemove={() => { setSettings({ ...settings, logo: undefined }); setSettingsState('unsaved') }} /><AssetField label="16:9 background image" asset={settings.background} accept="image/*" onFile={(file) => fileChange('background', file)} onRemove={() => { setSettings({ ...settings, background: undefined }); setSettingsState('unsaved') }} /></div></div> : null}
    {section === 'presentation' ? <div className="settings-presentation-grid"><div className="settings-form-grid settings-form-grid--two"><label>Safe-area margin (px)<input type="number" min="0" max="500" value={settings.safeAreaMargin} onChange={(e) => setSettings({ ...settings, safeAreaMargin: Number(e.target.value) })} /><span>Applied to the public Audience content boundary.</span></label><label>Blackout appearance<select value={settings.blackoutAppearance} onChange={(e) => setSettings({ ...settings, blackoutAppearance: e.target.value as EventSettings['blackoutAppearance'] })}><option value="pure-black">Pure black</option><option value="event-surface">Event surface</option></select><span>Shown when the public presentation is blacked out.</span></label></div><div className="settings-safe-area-preview" aria-label={`Safe-area preview with ${settings.safeAreaMargin}px margin`}><span>PUBLIC CONTENT BOUNDARY</span><strong>{settings.safeAreaMargin}px safe area</strong></div></div> : null}
    {section === 'audio' ? <div className="settings-audio-layout"><div className="settings-form-grid settings-form-grid--three"><label>Audio enabled<select value={settings.audioEnabled ? 'enabled' : 'disabled'} onChange={(e) => setSettings({ ...settings, audioEnabled: e.target.value === 'enabled' })}><option value="enabled">Enabled</option><option value="disabled">Disabled</option></select></label><label>Master volume (%)<div className="settings-volume-control"><input aria-label="Master volume" type="range" min="0" max="100" value={settings.masterVolume} onChange={(e) => setSettings({ ...settings, masterVolume: Number(e.target.value) })} /><output>{settings.masterVolume}%</output></div></label><AssetField label="Reveal cue audio" asset={settings.revealCue} accept="audio/*" onFile={(file) => fileChange('revealCue', file)} onRemove={() => { setSettings({ ...settings, revealCue: undefined }); setSettingsState('unsaved') }} /></div><div className="settings-audio-test"><Button type="button" variant="secondary" disabled={!settings.audioEnabled || settings.revealCue === undefined} onClick={() => void testAudio()}>Play / Test Audio</Button><span role="status">{audioMessage || (!settings.audioEnabled ? 'Enable audio to test the reveal cue.' : settings.revealCue === undefined ? 'Choose a valid reveal cue to test audio.' : '')}</span></div></div> : null}
    {section === 'display' ? <div className="settings-display-grid"><div className="settings-display-config"><label>Target resolution<select value={resolution} onChange={(e) => { setResolution(e.target.value); setSettingsState('unsaved') }}>{resolutions.map((item) => <option key={item.label} value={`${item.width}x${item.height}`}>{item.label}</option>)}</select></label><p className="settings-helper">The static preview uses the current Branding and Presentation draft without publishing a public snapshot.</p></div><AudiencePreviewSurface accentColor={currentSettings.accentColor} background={currentSettings.background} displayName={currentSettings.displayName} logo={currentSettings.logo} primaryColor={currentSettings.primaryColor} safeAreaMargin={currentSettings.safeAreaMargin} /><dl className="settings-display-meta"><div><dt>Aspect</dt><dd>16:9</dd></div><div><dt>Resolution</dt><dd>{selected.width} Ã— {selected.height}</dd></div><div><dt>Safe area</dt><dd>{currentSettings.safeAreaMargin}px</dd></div><div><dt>Runtime / test</dt><dd>{testVisibility === 'visible' ? 'Visible' : 'Inactive'}</dd></div></dl></div> : null}
    <div className="settings-action-row"><Button disabled={settingsState === 'saving' || !dirty} type="submit">{settingsState === 'saving' ? 'Saving...' : `Save ${section} settings`}</Button>{section === 'display' && displayUrl !== null ? <Button type="button" variant="secondary" onClick={openAudience}>Open Audience Display</Button> : null}{section === 'display' && displayUrl !== null ? <Button type="button" variant="secondary" disabled={testing} onClick={() => publishTest(true)}>{testing ? 'Publishing testâ€¦' : 'Test Display Connection'}</Button> : null}{testing ? <Button type="button" variant="danger" onClick={() => publishTest(false)}>Stop Test</Button> : null}</div></form>{section === 'display' ? <div className="settings-display-actions"><div className="settings-connection-panel"><strong>Connection status</strong><span className={`settings-connection settings-connection--${connection}`}>{labels[connection]}</span><span className={`settings-connection settings-connection--${testVisibility}`}>{testVisibility === 'visible' ? 'Test visible on Audience' : testVisibility === 'publishing' ? 'Publishing test' : testVisibility === 'failed' ? 'Publication rejected/failed' : 'Test inactive'}</span><p>Transport connection and public snapshot application are tracked separately.</p></div></div> : null}{section === 'display' && popupBlocked ? <div className="settings-popup-fallback" role="alert"><span>The browser blocked the new window.</span><Button type="button" variant="secondary" onClick={openAudience}>Open Audience Display</Button></div> : null}</article></div></div><p className="settings-back-link"><Link to="/dashboard">Return to Dashboard</Link></p></section>
}

function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="settings-color-field">{label}<span><input type="color" value={value} onChange={(e) => onChange(e.target.value)} /><input aria-label={`${label} hex`} value={value} onChange={(e) => onChange(e.target.value)} /></span></label> }
function AssetField({ label, asset, accept, onFile, onRemove }: { label: string; asset?: LocalAsset; accept: string; onFile: (file: File | undefined) => void; onRemove: () => void }) { const previewUrl = useMemo(() => asset !== undefined && asset.type.startsWith('image/') ? URL.createObjectURL(asset.blob) : null, [asset]); useEffect(() => previewUrl === null ? undefined : () => URL.revokeObjectURL(previewUrl), [previewUrl]); const isWide = label.includes('background'); return <div className={`settings-asset-field ${isWide ? 'settings-asset-field--wide' : 'settings-asset-field--logo'}`}><div className="settings-asset-field__preview">{previewUrl ? <img src={previewUrl} alt={`${label} preview`} /> : <span aria-hidden="true">{isWide ? '16:9' : 'LOGO'}</span>}</div><div className="settings-asset-field__copy"><strong>{label}</strong>{asset ? <small>{asset.name} Â· {(asset.size / 1024).toFixed(0)} KB</small> : <small>No local asset selected yet.</small>}<div className="settings-asset-field__actions"><label className="ui-button ui-button--secondary"><span>{asset ? 'Replace' : isWide ? 'Choose background' : 'Choose logo'}</span><input aria-label={`${asset ? 'Replace' : 'Choose'} ${label}`} type="file" accept={accept} onChange={(e) => onFile(e.target.files?.[0])} /></label>{asset ? <Button type="button" variant="quiet" onClick={onRemove}>Remove</Button> : null}</div></div></div> }
