import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore, type FormEvent } from 'react'
import { signalProductionWorkspaceChanged, useProductionAudiencePublisher, useProductionWorkspace } from '../../app/workspace/ProductionWorkspaceContext.tsx'
import { createDisplayConfigurationService } from '../../application/display/display-configuration-service.ts'
import type { DisplayConfiguration } from '../../domain/display/display-configuration.types.ts'
import { getDisplayConnectionStatus, subscribeDisplayConnectionStatus, type DisplayConnectionStatus } from '../../application/display-transport/connection-status.ts'
import { createEventSettingsService } from '../../application/settings/event-settings-service.ts'
import { CELEBRATION_EFFECTS, COUNTDOWN_DURATIONS_SECONDS, REVEAL_STYLES, ROLLING_DURATIONS_SECONDS, WINNER_LAYOUTS, type CelebrationEffect, type RevealStyle, type WinnerLayoutPreference } from '../../domain/settings/presentation-settings.types.ts'
import { validateAsset, type EventSettings, type LocalAsset } from '../../domain/settings/event-settings.types.ts'
import { parseDrawSessionId } from '../../domain/shared/identifiers.ts'
import { createDrawSetupProductionServices } from '../../infrastructure/composition/draw-command-production.ts'
import { PageHeader } from '../../shared/components/PageHeader.tsx'
import { StatusBanner } from '../../shared/components/StatusBanner.tsx'
import { Button } from '../../shared/ui/Button.tsx'
import { Icon } from '../../shared/ui/Icon.tsx'
import { useUiClass } from '../../shared/ui/ui-theme.ts'
import { AudiencePreviewSurface } from '../../ui/audience/AudiencePreviewSurface.tsx'
import { settingsEqual } from './production-settings-draft.ts'
import { SettingsSaveToast } from './SettingsSaveToast.tsx'
import { ProductionLoadingState, ProductionSetupRequired } from '../../shared/components/ProductionWorkspaceState.tsx'
import { formatAudioAssetSize, isValidRevealCue } from './audio-settings-ui.ts'
import { AudienceDisplayButton } from '../../shared/components/AudienceDisplayButton.tsx'

const resolutions = [{ label: '1920 × 1080 (Full HD)', width: 1920, height: 1080 }, { label: '3840 × 2160 (4K UHD)', width: 3840, height: 2160 }, { label: '1280 × 720 (HD)', width: 1280, height: 720 }] as const
const labels: Record<DisplayConnectionStatus, string> = { 'setup-required': 'Perlu pengaturan', waiting: 'Menunggu', connected: 'Terhubung', reconnecting: 'Menghubungkan kembali', unavailable: 'Tidak tersedia', 'publication-failed': 'Publikasi gagal' }
const settingsSectionIcons = { branding: 'Palette', presentation: 'SlidersHorizontal', audio: 'Volume2', display: 'Monitor' } as const
const assetFromFile = (file: File): LocalAsset => ({ name: file.name, type: file.type, size: file.size, blob: file })
const errorText = (error: unknown): string => error instanceof Error ? error.message : 'Pengaturan tidak dapat disimpan dengan aman.'
type SettingsSaveState = 'loading' | 'persisted' | 'unsaved' | 'saving' | 'saved' | 'error'
type SettingsToast = { readonly kind: 'success' | 'error'; readonly message: string }

export function ProductionSettingsPage() {
  const ui = useUiClass()
  const workspace = useProductionWorkspace(); const audience = useProductionAudiencePublisher(); const services = useMemo(() => createDrawSetupProductionServices(), [])
  const settingsService = useMemo(() => createEventSettingsService(services.eventSettings), [services]); const displayService = useMemo(() => createDisplayConfigurationService({ events: services.events, configurations: services.displayConfigurations! }), [services])
  const [settings, setSettings] = useState<EventSettings | null>(null); const [persistedSettings, setPersistedSettings] = useState<EventSettings | null>(null); const [activeDisplay, setActiveDisplay] = useState<DisplayConfiguration | null>(null); const [section, setSection] = useState<'branding' | 'presentation' | 'audio' | 'display'>('branding')
  const [resolution, setResolution] = useState('1920x1080'); const [persistedResolution, setPersistedResolution] = useState('1920x1080'); const [safeAreaMargin, setSafeAreaMargin] = useState(0); const [persistedSafeAreaMargin, setPersistedSafeAreaMargin] = useState(0); const [blackoutAppearance, setBlackoutAppearance] = useState<'pure-black'>('pure-black'); const [persistedBlackoutAppearance, setPersistedBlackoutAppearance] = useState<'pure-black'>('pure-black')
  const initiallyTestActive = audience.getDiagnostics()?.retainedPublicState === 'display-test'; const [settingsState, setSettingsState] = useState<SettingsSaveState>('loading'); const [message, setMessage] = useState<string | null>(null); const [toast, setToast] = useState<SettingsToast | null>(null); const [testing, setTesting] = useState(initiallyTestActive); const [testVisibility, setTestVisibility] = useState<'inactive' | 'publishing' | 'visible' | 'stopping' | 'standby' | 'failed'>(initiallyTestActive ? 'visible' : 'inactive'); const [popupBlocked, setPopupBlocked] = useState(false); const [audioMessage, setAudioMessage] = useState(''); const testVisibilityRef = useRef(testVisibility)
  const displayStatusKey = workspace.status === 'ready' && activeDisplay !== null ? `${workspace.event.id}:${activeDisplay.id}` : 'unconfigured'; const connection = useSyncExternalStore((listener) => subscribeDisplayConnectionStatus(displayStatusKey, listener), () => getDisplayConnectionStatus(displayStatusKey), () => 'waiting' as DisplayConnectionStatus)
  useEffect(() => { testVisibilityRef.current = testVisibility }, [testVisibility])
  const load = useCallback(async () => { if (workspace.status !== 'ready') return; setSettingsState('loading'); try { await services.open(); const loaded = await settingsService.readForEvent(workspace.event); const display = await displayService.readForEvent(workspace.event); const loadedResolution = `${display?.targetResolution.width ?? 1920}x${display?.targetResolution.height ?? 1080}`; const margin = display?.safeAreaMargin ?? 0; const blackout = display?.blackoutAppearance ?? 'pure-black'; setSettings(loaded); setPersistedSettings(loaded); setActiveDisplay(display); setResolution(loadedResolution); setPersistedResolution(loadedResolution); setSafeAreaMargin(margin); setPersistedSafeAreaMargin(margin); setBlackoutAppearance(blackout); setPersistedBlackoutAppearance(blackout); setSettingsState('persisted') } catch (error: unknown) { setSettingsState('error'); setMessage(errorText(error)) } }, [displayService, services, settingsService, workspace])
  useEffect(() => { void Promise.resolve().then(load) }, [load])
  useEffect(() => audience.subscribe((status) => { const retainedState = audience.getDiagnostics()?.retainedPublicState; if (retainedState === 'display-test') { setTesting(true); setTestVisibility('visible') }; if (retainedState === 'standby' && testVisibilityRef.current !== 'publishing') { setTesting(false); setTestVisibility('standby') }; if (status.kind === 'snapshot-applied' && status.publicState === 'display-test') { setTesting(true); setTestVisibility('visible') }; if (status.kind === 'snapshot-applied' && status.publicState === 'standby' && testVisibilityRef.current === 'stopping') { setTesting(false); setTestVisibility('standby') }; if (status.kind === 'transport-error') { setTestVisibility('failed'); setMessage('Snapshot tampilan tidak dapat dipublikasikan dengan aman.') } }), [audience])
  if (workspace.status !== 'ready') return <section aria-labelledby="settings-title"><PageHeader eyebrow="Ruang kerja produksi" headingId="settings-title" title="Pengaturan" description="Acara aktif diperlukan." /><ProductionSetupRequired title="Acara diperlukan" description="Pilih Acara sebelum mengatur produksi." /></section>
  if (settings === null) return <section aria-busy="true"><PageHeader eyebrow="Ruang kerja produksi" headingId="settings-title" title="Pengaturan" description="Membaca Pengaturan Acara resmi…" /><ProductionLoadingState description="Membaca Pengaturan Acara resmi…" />{settingsState === 'error' ? <StatusBanner badge="Kesalahan penyimpanan" title="Pengaturan tidak tersedia" tone="warning">{message}</StatusBanner> : null}</section>
  const event = workspace.event; const currentSettings = settings; const displayUrl = activeDisplay === null ? null : `/display?eventId=${encodeURIComponent(event.id)}&displayConfigurationId=${encodeURIComponent(activeDisplay.id)}`; const selected = resolutions.find((item) => `${item.width}x${item.height}` === resolution) ?? resolutions[0]
  const dirty = persistedSettings !== null && (activeDisplay === null || !settingsEqual(currentSettings, persistedSettings) || resolution !== persistedResolution || safeAreaMargin !== persistedSafeAreaMargin || blackoutAppearance !== persistedBlackoutAppearance); const sectionDetails = { branding: ['Branding', 'BRANDING', 'Identitas Acara', 'Tentukan identitas publik yang digunakan pada Tampilan Audiens.'], presentation: ['Presentasi', 'PRESENTASI', 'Perilaku presentasi', 'Atur waktu, pengungkapan, perayaan, gerakan, dan preferensi layout pemenang.'], audio: ['Audio', 'AUDIO', 'Isyarat audio', 'Atur isyarat opsional saat pengungkapan publik.'], display: ['Tampilan', 'TAMPILAN', 'Tampilan Audiens', 'Kontrol koneksi tampilan publik dan bingkai target.'] } as const; const details = sectionDetails[section]; const effective = settingsState === 'saving' ? 'Menyimpan' : dirty ? 'Perubahan belum disimpan' : settingsState === 'error' ? 'Perlu perhatian' : activeDisplay === null ? 'Perlu pengaturan' : 'Tersimpan'
  async function save(eventSubmit: FormEvent<HTMLFormElement>) { eventSubmit.preventDefault(); if (settingsState === 'saving' || !dirty) return; setSettingsState('saving'); setMessage(null); setToast(null); try { const saved = await settingsService.saveForEvent(event, { ...currentSettings }); const display = await displayService.saveForEvent(event, { targetResolution: { width: selected.width, height: selected.height }, safeAreaMargin, blackoutAppearance }, activeDisplay); setActiveDisplay(display); setSettings(saved); setPersistedSettings(saved); setPersistedResolution(resolution); setPersistedSafeAreaMargin(safeAreaMargin); setPersistedBlackoutAppearance(blackoutAppearance); setSettingsState('saved'); signalProductionWorkspaceChanged(); setToast({ kind: 'success', message: `Pengaturan ${details[0]} tersimpan` }) } catch (error: unknown) { setSettingsState('error'); setMessage(errorText(error)); setToast({ kind: 'error', message: `Pengaturan ${details[0]} tidak dapat disimpan. Coba lagi.` }) } }
  function fileChange(field: 'logo' | 'background' | 'revealCue', file: File | undefined) { if (file === undefined) return; const asset = assetFromFile(file); const validationError = field === 'revealCue' ? validateAsset(asset, 'audio') : null; if (validationError !== null) { setAudioMessage(validationError); return }; setSettings((current) => current === null ? current : { ...current, [field]: asset }); setSettingsState('unsaved'); if (field === 'revealCue') setAudioMessage('') }
  function publishTest(displayTest: boolean) { if (activeDisplay === null) return; const parsed = parseDrawSessionId(event.id); if (!parsed.ok) { setMessage('Acara aktif tidak dapat membatasi tes tampilan dengan aman.'); return }; if (!displayTest) { setTestVisibility('stopping'); setTesting(false) } else { setTesting(true); setTestVisibility('publishing') }; const result = audience.publish({ drawSessionId: parsed.value, stage: 'standby', blackoutRequested: false, displayTest, eventName: currentSettings.displayName, eventSubtitle: currentSettings.subtitle, primaryColor: currentSettings.primaryColor, accentColor: currentSettings.accentColor, logo: currentSettings.logo === undefined ? undefined : { type: currentSettings.logo.type, blob: currentSettings.logo.blob }, background: currentSettings.background === undefined ? undefined : { type: currentSettings.background.type, blob: currentSettings.background.blob }, blackoutAppearance, safeAreaMargin }); if (!result.ok) setTestVisibility('failed') }
  async function testAudio() { if (!currentSettings.audioEnabled) { setAudioMessage('Aktifkan audio sebelum menguji isyarat pengungkapan.'); return }; if (!isValidRevealCue(currentSettings.revealCue)) { setAudioMessage('Pilih file audio lokal yang valid sebelum menguji isyarat.'); return }; try { const audio = new Audio(URL.createObjectURL(currentSettings.revealCue.blob)); audio.volume = currentSettings.masterVolume / 100; await audio.play(); setAudioMessage('Isyarat diputar setelah tindakan Anda.'); audio.onended = () => URL.revokeObjectURL(audio.src) } catch { setAudioMessage('Izin audio browser diperlukan; tekan Uji Audio lagi setelah mengizinkan pemutaran.') } }
  return <section aria-labelledby="settings-title" className="production-settings"><PageHeader actions={displayUrl === null ? undefined : <AudienceDisplayButton displayUrl={displayUrl} onPopupBlocked={setPopupBlocked} variant="secondary" />} eyebrow="Ruang kerja produksi" headingId="settings-title" title="Pengaturan" description={`${event.name} · presentasi Acara resmi`} />{message ? <StatusBanner badge="Pengaturan" title="Tindakan perlu perhatian" tone="warning">{message}</StatusBanner> : null}{toast ? <SettingsSaveToast key={`${toast.kind}:${toast.message}`} kind={toast.kind} message={toast.message} onDismiss={() => setToast(null)} /> : null}<div className="settings-workspace"><nav aria-label="Bagian Pengaturan" className="settings-section-nav"><p>PENGATURAN</p>{(['branding', 'presentation', 'audio', 'display'] as const).map((item) => <button type="button" key={item} className={section === item ? 'is-active' : undefined} aria-current={section === item ? 'page' : undefined} onClick={() => setSection(item)}><Icon name={settingsSectionIcons[item]} size={18} /><strong>{sectionDetails[item][0]}</strong></button>)}</nav><div className="settings-content"><article className="settings-card"><div className="settings-card__heading"><div><p className="settings-card__eyebrow">{details[1]}</p><h2>{details[2]}</h2><p className="settings-card__description">{details[3]}</p></div><span className={`settings-authority settings-authority--${effective.toLowerCase().replace(' ', '-')}`}>{effective}</span></div><form onSubmit={save} aria-label={`Pengaturan ${details[0]}`}>
    {section === 'branding' ? <div className="settings-branding-layout"><div className="settings-form-grid settings-form-grid--branding"><label>Nama tampilan publik<input className={ui('ui-input')} value={settings.displayName} onChange={(e) => setSettings({ ...settings, displayName: e.target.value })} /></label><label>Subjudul publik<input className={ui('ui-input')} value={settings.subtitle} onChange={(e) => setSettings({ ...settings, subtitle: e.target.value })} /></label><ColorField label="Warna utama" value={settings.primaryColor} onChange={(value) => setSettings({ ...settings, primaryColor: value })} /><ColorField label="Warna aksen" value={settings.accentColor} onChange={(value) => setSettings({ ...settings, accentColor: value })} /></div><div className="settings-asset-grid"><AssetField label="Logo Acara" asset={settings.logo} accept="image/*" onFile={(file) => fileChange('logo', file)} onRemove={() => { setSettings({ ...settings, logo: undefined }); setSettingsState('unsaved') }} /><AssetField label="Gambar latar 16:9" asset={settings.background} accept="image/*" onFile={(file) => fileChange('background', file)} onRemove={() => { setSettings({ ...settings, background: undefined }); setSettingsState('unsaved') }} /></div></div> : null}
    {section === 'presentation' ? <div className="settings-form-grid settings-form-grid--two settings-presentation-grid"><PresentationSelect label="Durasi hitung mundur" value={settings.presentation.countdownDurationSeconds} options={COUNTDOWN_DURATIONS_SECONDS.map((value) => [value, `${value} detik`])} onChange={(value) => setSettings({ ...settings, presentation: { ...settings.presentation, countdownDurationSeconds: value as typeof settings.presentation.countdownDurationSeconds } })} help="Waktu sebelum undian publik dimulai." /><PresentationSelect label="Durasi pengacakan" value={settings.presentation.rollingDurationSeconds} options={ROLLING_DURATIONS_SECONDS.map((value) => [value, `${value} detik`])} onChange={(value) => setSettings({ ...settings, presentation: { ...settings.presentation, rollingDurationSeconds: value as typeof settings.presentation.rollingDurationSeconds } })} help="Waktu untuk presentasi pengacakan tiket." /><PresentationSelect label="Gaya pengungkapan" value={settings.presentation.revealStyle} options={REVEAL_STYLES.map((value) => [value, revealLabel(value)])} onChange={(value) => setSettings({ ...settings, presentation: { ...settings.presentation, revealStyle: value as RevealStyle } })} /><PresentationSelect label="Efek perayaan" value={settings.presentation.celebrationEffect} options={CELEBRATION_EFFECTS.map((value) => [value, celebrationLabel(value)])} onChange={(value) => setSettings({ ...settings, presentation: { ...settings.presentation, celebrationEffect: value as CelebrationEffect } })} /><label className="settings-toggle-field"><span>Hormati preferensi pengurangan gerakan</span><span className="settings-toggle-field__control"><input type="checkbox" checked={settings.presentation.respectReducedMotion} onChange={(e) => setSettings({ ...settings, presentation: { ...settings.presentation, respectReducedMotion: e.target.checked } })} /><small>Gunakan gerakan terbatas saat diminta oleh browser.</small></span></label><PresentationSelect label="Preferensi tata letak pemenang" value={settings.presentation.winnerLayoutPreference} options={WINNER_LAYOUTS.map((value) => [value, winnerLayoutLabel(value)])} onChange={(value) => setSettings({ ...settings, presentation: { ...settings.presentation, winnerLayoutPreference: value as WinnerLayoutPreference } })} /></div> : null}
    {section === 'audio' ? <div className="settings-audio-layout"><div className="settings-audio-columns"><div className="settings-audio-controls"><label className="ui-toggle settings-audio-enabled-toggle" htmlFor="audio-enabled"><span className="ui-toggle__copy"><span className="ui-toggle__label">Audio aktif</span><span className="ui-toggle__description">Izinkan isyarat pengungkapan diputar pada Tampilan Audiens.</span></span><span className="settings-audio-enabled-toggle__control"><span className="settings-audio-enabled-toggle__state">{settings.audioEnabled ? 'Aktif' : 'Nonaktif'}</span><input aria-checked={settings.audioEnabled} aria-label="Audio aktif" checked={settings.audioEnabled} className="ui-toggle__input" id="audio-enabled" onChange={(e) => setSettings({ ...settings, audioEnabled: e.target.checked })} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); setSettings({ ...settings, audioEnabled: !settings.audioEnabled }) } }} role="switch" type="checkbox" /><span aria-hidden="true" className="ui-toggle__track"><span className="ui-toggle__thumb" /></span></span></label><div className={`settings-volume-block ${!settings.audioEnabled ? 'is-disabled' : ''}`}><div className="settings-volume-block__header"><strong>Volume utama</strong><output>{settings.masterVolume}%</output></div><div className="settings-volume-control"><input aria-label="Volume utama" disabled={!settings.audioEnabled} type="range" min="0" max="100" value={settings.masterVolume} onChange={(e) => setSettings({ ...settings, masterVolume: Number(e.target.value) })} /></div><p>{settings.audioEnabled ? 'Atur tingkat keluaran untuk isyarat yang dipilih.' : 'Aktifkan audio untuk mengatur tingkat pemutaran.'}</p></div></div><AudioAssetField asset={settings.revealCue} onFile={(file) => fileChange('revealCue', file)} onRemove={() => { setSettings({ ...settings, revealCue: undefined }); setSettingsState('unsaved'); setAudioMessage('Isyarat pengungkapan dihapus.'); }} /></div><div className="settings-audio-test"><Button icon={<Icon name="Play" />} type="button" variant="secondary" disabled={!settings.audioEnabled || !isValidRevealCue(settings.revealCue)} onClick={() => void testAudio()}>Putar / Uji Audio</Button><span role="status">{audioMessage || (!settings.audioEnabled ? 'Aktifkan audio untuk menguji isyarat pengungkapan.' : !isValidRevealCue(settings.revealCue) ? 'Pilih file audio lokal yang valid untuk mengaktifkan pengujian.' : 'Siap menguji isyarat pengungkapan.')}</span></div></div> : null}
    {section === 'display' ? <div className="settings-display-grid"><div className="settings-display-config"><div className="settings-display-config__group"><div className="settings-display-config__group-heading">Bingkai keluaran</div><label>Resolusi target<select className={ui('ui-input')} value={resolution} onChange={(e) => { setResolution(e.target.value); setSettingsState('unsaved') }}>{resolutions.map((item) => <option key={item.label} value={`${item.width}x${item.height}`}>{item.label}</option>)}</select><span className="settings-display-config__helper">Pilih bingkai keluaran untuk Tampilan Audiens.</span></label><label>Margin area aman<div className="settings-display-config__unit-control"><input className={ui('ui-input')} type="number" min="0" max="500" value={safeAreaMargin} onChange={(e) => { setSafeAreaMargin(Number(e.target.value)); setSettingsState('unsaved') }} /><span aria-hidden="true">px</span></div><span className="settings-display-config__helper">Pertahankan branding dan konten undian di dalam batas ini.</span></label></div><div className="settings-display-config__group settings-display-config__group--safety"><div className="settings-display-config__group-heading">Perilaku keselamatan</div><label>Tampilan layar hitam<select className={ui('ui-input')} value={blackoutAppearance} onChange={(e) => { setBlackoutAppearance(e.target.value as 'pure-black'); setSettingsState('unsaved') }}><option value="pure-black">Hitam pekat</option></select><span className="settings-display-config__helper">Gunakan hitam pekat saat layar hitam diminta. Tampilan mengelola bingkai dan perilaku layar hitam.</span></label></div></div><AudiencePreviewSurface accentColor={currentSettings.accentColor} background={currentSettings.background} displayName={currentSettings.displayName} logo={currentSettings.logo} primaryColor={currentSettings.primaryColor} safeAreaMargin={safeAreaMargin} /><dl className="settings-display-meta"><div><dt>Aspek</dt><dd>16:9</dd></div><div><dt>Resolusi</dt><dd>{selected.width} × {selected.height}</dd></div><div><dt>Area aman</dt><dd>{safeAreaMargin}px</dd></div><div><dt>Runtime / tes</dt><dd>{testVisibility === 'visible' ? 'Terlihat' : 'Tidak aktif'}</dd></div></dl></div> : null}
    <div className="settings-action-row"><Button icon={<Icon name="Save" />} disabled={settingsState === 'saving' || !dirty} type="submit">{settingsState === 'saving' ? 'Menyimpan…' : `Simpan Pengaturan ${details[0]}`}</Button>{section === 'display' && displayUrl !== null ? <AudienceDisplayButton displayUrl={displayUrl} onPopupBlocked={setPopupBlocked} variant="secondary" /> : null}{section === 'display' && displayUrl !== null ? <Button icon={<Icon name="MonitorCheck" />} type="button" variant="secondary" disabled={testing} onClick={() => publishTest(true)}>{testing ? 'Mempublikasikan tes…' : 'Uji Koneksi Tampilan'}</Button> : null}{testing ? <Button icon={<Icon name="StopCircle" />} type="button" variant="danger" onClick={() => publishTest(false)}>Hentikan Tes</Button> : null}</div></form>{section === 'display' ? <div className="settings-display-actions"><div aria-atomic="true" aria-live="polite" className="settings-connection-panel" role="status"><strong>Status koneksi</strong><span className={`settings-connection settings-connection--${connection}`}>{labels[connection]}</span><span className={`settings-connection settings-connection--${testVisibility}`}>{testVisibility === 'visible' ? 'Tes terlihat pada Audiens' : testVisibility === 'publishing' ? 'Mempublikasikan tes' : testVisibility === 'failed' ? 'Publikasi ditolak/gagal' : 'Tes tidak aktif'}</span><p>Koneksi transport dan penerapan snapshot publik dilacak secara terpisah.</p></div></div> : null}{section === 'display' && popupBlocked && displayUrl !== null ? <div className="settings-popup-fallback" role="alert"><span>Browser memblokir jendela baru.</span><AudienceDisplayButton displayUrl={displayUrl} onPopupBlocked={setPopupBlocked} variant="secondary" /></div> : null}</article></div></div></section>
}

function PresentationSelect({ label, value, options, onChange, help }: { readonly label: string; readonly value: string | number; readonly options: readonly (readonly [string | number, string])[]; readonly onChange: (value: string | number) => void; readonly help?: string }) { const ui = useUiClass(); return <label>{label}<select className={ui('ui-input')} value={value} onChange={(e) => { const option = options.find(([key]) => String(key) === e.target.value); if (option !== undefined) onChange(option[0]) }}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select>{help ? <span>{help}</span> : null}</label> }
function revealLabel(value: RevealStyle): string { return { 'ticket-spotlight': 'Sorotan tiket', 'instant-reveal': 'Ungkap langsung', 'sequential-reveal': 'Ungkap berurutan' }[value] }
function celebrationLabel(value: CelebrationEffect): string { return { 'confetti-burst': 'Ledakan konfeti', 'light-sweep': 'Sapuan cahaya', none: 'Tidak ada' }[value] }
function winnerLayoutLabel(value: WinnerLayoutPreference): string { return { 'adaptive-operator-preview': 'Pratinjau Operator adaptif', 'single-hero': 'Satu utama', 'compact-grid': 'Grid ringkas' }[value] }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { const ui = useUiClass(); return <label className="settings-color-field">{label}<span><input className={ui('ui-input')} aria-label={`Pemilih ${label}`} type="color" value={value} onChange={(e) => onChange(e.target.value)} /><input className={ui('ui-input')} aria-label={`Nilai heksadesimal ${label}`} value={value} onChange={(e) => onChange(e.target.value)} /></span></label> }
function AssetField({ label, asset, accept, onFile, onRemove }: { label: string; asset?: LocalAsset; accept: string; onFile: (file: File | undefined) => void; onRemove: () => void }) { const ui = useUiClass(); const previewUrl = useMemo(() => asset !== undefined && asset.type.startsWith('image/') ? URL.createObjectURL(asset.blob) : null, [asset]); useEffect(() => previewUrl === null ? undefined : () => URL.revokeObjectURL(previewUrl), [previewUrl]); const isWide = label.includes('latar'); return <div className={`settings-asset-field ${isWide ? 'settings-asset-field--wide' : 'settings-asset-field--logo'}`}><div className="settings-asset-field__preview">{previewUrl ? <img src={previewUrl} alt={`Pratinjau ${label}`} /> : <span aria-hidden="true">{isWide ? '16:9' : 'LOGO'}</span>}</div><div className="settings-asset-field__copy"><strong>{label}</strong>{asset ? <small>{asset.name} · {(asset.size / 1024).toFixed(0)} KB</small> : <small>Belum ada aset lokal dipilih.</small>}<div className="settings-asset-field__actions"><label className={ui('ui-button ui-button--secondary ui-button--sm')}><span aria-hidden="true" className={ui('ui-button__icon')}><Icon name="Upload" /></span><span>{asset ? 'Ganti' : isWide ? 'Pilih latar' : 'Pilih logo'}</span><input aria-label={`${asset ? 'Ganti' : 'Pilih'} ${label}`} type="file" accept={accept} onChange={(e) => onFile(e.target.files?.[0])} /></label>{asset ? <Button icon={<Icon name="Trash2" />} type="button" variant="quiet" onClick={onRemove}>Hapus</Button> : null}</div></div></div> }
function AudioAssetField({ asset, onFile, onRemove }: { asset?: LocalAsset; onFile: (file: File | undefined) => void; onRemove: () => void }) { const ui = useUiClass(); return <div className="settings-audio-asset"><div className="settings-audio-asset__visual" aria-hidden="true"><span>♫</span><i /><i /><i /><i /><i /></div><div className="settings-audio-asset__body"><div><strong>Audio isyarat pengungkapan</strong><small>{asset ? `${asset.name} · ${formatAudioAssetSize(asset.size)}` : 'Belum ada aset audio lokal dipilih.'}</small></div><div className="settings-audio-asset__actions"><label className={ui('ui-button ui-button--secondary ui-button--sm')}><span aria-hidden="true" className={ui('ui-button__icon')}><Icon name="Upload" /></span><span>{asset ? 'Ganti' : 'Pilih audio'}</span><input aria-label={`${asset ? 'Ganti' : 'Pilih'} audio isyarat pengungkapan`} type="file" accept="audio/*" onChange={(e) => onFile(e.target.files?.[0])} /></label>{asset ? <Button icon={<Icon name="Trash2" />} type="button" variant="quiet" onClick={onRemove}>Hapus</Button> : null}</div></div></div> }
