<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <StartupObject>Kocokan.VisualReview</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../launcher/*.cs" Link="Launcher/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
